# Generated by Django 4.1.1 on 2022-10-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='defaultDp.jpg', null=True, upload_to=''),
        ),
    ]
